travis:
  secure:
    BINSTAR_TOKEN: FqP6nBKnHP/U9CZliHxmZefGQxyYX62EVrFpw++UMAUDYu8YpzUXXc+KHVi+jnbyotzQ5WyX0XT7vqq3kZJqGdYCptW87zNXo8XRKafSiw7IfUWPGOSSMlmzFF2UClc723Hmj3N1ki87xi87BWXtItuQFzj9zP6rmV0bFkTU0cf5vmFKXjA6J9/0oKiATsamJk55b7brcvrDnsLjcmr6rBW8Nklf9JLa5rnvfpHroQEgNlJ5WLIHSL/rTfbulq8De6Mg/XYqQnvxsRc2+AVqpFCP0m3Lr1/MPtiaNxtoUWllJfDylJjHvaefkWvX6teuuM95o8jq+S2bDzuouT07FE6a3zJaaO2Q+Fa46W70022a/Npdj1sIMnY3dIBWerj2lNKRG0gYcw1rM18fchgmaWd8fT5ocXobVI2pEuazETRq2WaFQGpYTim8S6YGCccQ5l8ew+U6Y171vOKs4ZEdjLZJ9xvozhwOAp2LOgFawa6JSYenxWI1ykdTDsX/Y04XldkF5LLnheyPcmf/iCWwJdW5P3rk1SQG7oUzZavXe2N3XZWcXV0hAUnJBiEY6eX72WvGNLTA531PWqry5APUVuKEAPtN+xeWEkZbtegXyNlA8qgCP8tsysRy0mj4OIVqAgaefD80murECHzDjdWNBMm+dUy6yRwT4ImuEf8U7C0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
